# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98893edb96e05f16dc267b3b43e1d7696c24535a55ba47fc57f62bec16d7fbe42dfab75026be26f463040f721b400c2aa3780dfd02df44451b2d6ca9e7a6cc80

test:
  secret_key_base: 946f5637f7828a2c711a9ca640a21f255181fe07be1672ecffa5e104be338136345a7060ba79ea7f7e4a0acd023f6e92dfff7d08a246d36ded67bf378f3e0912

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
